version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  SONAR_APIKEY:
    secure: DUCuBgLmhR6jEJEm0n480wMqRFLsCLfhucK9zqPzbxmWg6Dxl9IS3rehXprs8jTn
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: $(appveyor_build_version)
init:
- ps: choco install "msbuild-sonarqube-runner" -y
- ps: Get-ChildItem -Recurse
install:
- ps: dotnet restore .\NipValidator.sln
before_build:
- ps: .\tools\sonar-scanner-msbuild\SonarQube.Scanner.MSBuild.exe begin /d:sonar.organization="rychu-pawel-github" /k:NipValidator /d:sonar.login=$env:SONAR_APIKEY /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="**/*.trx"
build_script:
- ps: dotnet build .\NipValidator.sln -c Release
test_script:
- ps: dotnet test .\tests\NipValidatorTests\NipValidatorTests.csproj --logger:trx
after_test:
- ps: .\tools\sonar-scanner-msbuild\SonarQube.Scanner.MSBuild.exe end /d:sonar.login=$env:SONAR_APIKEY
artifacts:
- path: .\src\NipValidator\bin\Release\Rychusoft.Validators.NipValidator.*.nupkg
  name: NipValidator_nuget_package
deploy:
- provider: NuGet
  api_key:
    secure: zC91fFY1joZMkDXOAgrK/3jppgEntX9lWV8wtQr1Da8hENFmY9emqRqgaBLyGlg3
  artifact: NipValidator_nuget_package
  on:
    branch: master
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false