version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: $(appveyor_build_version)
init:
- ps: Write-Host $MyInvocation.InvocationName
- ps: Write-Host $PSScriptRoot
- ps: Write-Host $MyInvocation.MyCommand.Definition
- ps: Write-Host split-path -parent $MyInvocation.MyCommand.Definition
- ps: Write-Host (split-path -parent $MyInvocation.MyCommand.Definition) + "\scipts\AppVeyor\init.ps1"
- ps: Write-Host ($PSScriptRoot) + "\scipts\AppVeyor\init.ps1"
- ps: Write-Host $PSScriptRoot "\scipts\AppVeyor\init.ps1"
- ps: Write-Host $PSScriptRoot + "\scipts\AppVeyor\init.ps1"
- ps: '& ((Split-Path $MyInvocation.InvocationName) + "\scipts\AppVeyor\init.ps1")'
install:
- ps: '& "scripts\AppVeyor\install.ps1"'
before_build:
- ps: '& "scripts\AppVeyor\before_build.ps1"'
build_script:
- ps: '& "scripts\AppVeyor\build.ps1"'
after_build:
- ps: '& "scripts\AppVeyor\after_build.ps1"'
test_script:
- ps: '& "scripts\AppVeyor\test.ps1"'
after_test:
- ps: '& "scripts\AppVeyor\after_test.ps1"'
artifacts:
- path: .\src\NipValidator\bin\Release\Rychusoft.Validators.NipValidator.*.nupkg
  name: NipValidator_nuget_package
deploy:
- provider: NuGet
  api_key:
    secure: zC91fFY1joZMkDXOAgrK/3jppgEntX9lWV8wtQr1Da8hENFmY9emqRqgaBLyGlg3
  artifact: NipValidator_nuget_package
  on:
    branch: master
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false